/***************************************************************************
 *  qgsllamawebuiplugin.cpp                                                *
 *                                                                         *
 *  This program is free software; you can redistribute it and/or modify   *
 *  it under the terms of the GNU General Public License as published by   *
 *  the Free Software Foundation; either version 2 of the License, or      *
 *  (at your option) any later version.                                    *
 *                                                                         *
 ***************************************************************************/

#include "qgsllamawebuiplugin.h"
#include "moc_qgsllamawebuiplugin.cpp"

#include "qgisinterface.h"
#include "qgsllamawebuidock.h"

#include <QAction>
#include <QIcon>

QgsLlamaWebuiPlugin::QgsLlamaWebuiPlugin( QgisInterface *iface )
  : QgisPlugin( sName, sDescription, sCategory, sPluginVersion, sPluginType )
  , mIface( iface )
{
}

void QgsLlamaWebuiPlugin::initGui()
{
  ensureDock();

  mToggleAction = new QAction( QIcon( sPluginIcon ), tr( "LLM Web UI" ), this );
  mToggleAction->setObjectName( QStringLiteral( "LlamaWebUiAction" ) );
  mToggleAction->setCheckable( true );

  // Keep the dock and action visibility in sync.
  mDock->setToggleVisibilityAction( mToggleAction );

  mIface->addPluginToMenu( sName, mToggleAction );
  mIface->addToolBarIcon( mToggleAction );
}

void QgsLlamaWebuiPlugin::unload()
{
  if ( mIface && mToggleAction )
  {
    mIface->removePluginMenu( sName, mToggleAction );
    mIface->removeToolBarIcon( mToggleAction );
  }

  delete mToggleAction;
  mToggleAction = nullptr;

  if ( mIface && mDock )
  {
    mIface->removeDockWidget( mDock );
  }
  delete mDock;
  mDock = nullptr;
}

void QgsLlamaWebuiPlugin::ensureDock()
{
  if ( mDock || !mIface )
    return;

  mDock = new QgsLlamaWebuiDockWidget( mIface->mainWindow() );
  mDock->setObjectName( QStringLiteral( "LlamaWebUiDock" ) );
  mDock->hide();
  mIface->addDockWidget( Qt::RightDockWidgetArea, mDock );
}


//////////////////////////////////////////////////////////////////////////
//
//
//  THE FOLLOWING CODE IS AUTOGENERATED BY THE PLUGIN BUILDER SCRIPT
//    YOU WOULD NORMALLY NOT NEED TO MODIFY THIS, AND YOUR PLUGIN
//      MAY NOT WORK PROPERLY IF YOU MODIFY THIS INCORRECTLY
//
//
//////////////////////////////////////////////////////////////////////////


/**
 * Required extern functions needed  for every plugin
 * These functions can be called prior to creating an instance
 * of the plugin class
 */
// Class factory to return a new instance of the plugin class
QGISEXTERN QgisPlugin *classFactory( QgisInterface *qgisInterfacePointer )
{
  return new QgsLlamaWebuiPlugin( qgisInterfacePointer );
}
// Return the name of the plugin - note that we do not use class members as
// the class may not yet be instantiated when this method is called.
QGISEXTERN const QString *name()
{
  return &sName;
}

// Return the description
QGISEXTERN const QString *description()
{
  return &sDescription;
}

// Return the category
QGISEXTERN const QString *category()
{
  return &sCategory;
}

// Return the type (either UI or MapLayer plugin)
QGISEXTERN int type()
{
  return sPluginType;
}

// Return the version number for the plugin
QGISEXTERN const QString *version()
{
  return &sPluginVersion;
}

QGISEXTERN const QString *icon()
{
  return &sPluginIcon;
}

// Delete ourself
QGISEXTERN void unload( QgisPlugin *pluginPointer )
{
  delete pluginPointer;
}
