# -*- coding: utf-8 -*-
"""
/***************************************************************************
dataEncodeConvertDialog
                                 A QGIS plugin
 DataEncodeConvert
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-25
        git sha              : $Format:%H$
        copyright            : (C) 2024 by 星球
        email                : 星球
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import glob
import shutil
from qgis.PyQt import uic, QtWidgets
from decimal import Decimal
from PyQt5.QtWidgets import QFileDialog, QMessageBox, QApplication
from PyQt5.QtCore import QThread, pyqtSignal, QVariant, QSettings
from os.path import split, splitext
import concurrent.futures
from osgeo import ogr
from qgis.core import QgsVectorLayer, QgsWkbTypes, QgsProviderRegistry, QgsVectorFileWriter, QgsProject, QgsCoordinateTransform, QgsField, QgsFeature,QgsMessageLog, Qgis
# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'dataFieldOptimization_dialog_base.ui'))


class dataFieldOptimizationDialog(QtWidgets.QDialog, FORM_CLASS):
    progress_signal = pyqtSignal(int, str)

    def __init__(self, parent=None, showDlg=True):
        """Constructor."""
        super(dataFieldOptimizationDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.showDlg = showDlg
        self.max_thread_num = 100

        #浏览数据目录
        self.inputPushButton.clicked.connect(self.on_data_dir_clicked)
        #浏览配置文件
        self.configPushButton.clicked.connect(self.on_data_config_clicked)
        #浏日志文件
        self.logPushButton.clicked.connect(self.on_data_log_clicked)
        #浏览处理结果目录
        self.outputPushButton.clicked.connect(self.on_data_op_clicked)
        
        #开始处理
        self.processPushButton.clicked.connect(self.on_process_button_clicked)

        #关闭对话框
        self.closeButton.clicked.connect(self.on_close_button_clicked)

        self.settings = QSettings('XingqiuCompany', 'dataFieldOptimization')
        self.inputLineEdit.setText(self.settings.value('data_path', ''))
        self.configLineEdit.setText(self.settings.value('config_path', ''))
        self.logLineEdit.setText(self.settings.value('log_path', ''))
        self.outputLineEdit.setText(self.settings.value('op_path', ''))

        dataType = self.settings.value('data_type', 0, type=int)
        if dataType == 0:
            self.shpRadioButton.setChecked(True)
        else:
            self.gpkgRadioButton.setChecked(True)

        self.progress_signal.connect(self.connect_fun)

    def connect_fun(self, prog, msg_data):
        if self.showDlg:
            self.progressBar.setValue(prog)
        else:
            print("当前进度:" + str(prog) + "%")

        if prog >= 100:
            if self.showDlg:
                QMessageBox.information(None, '提示', msg_data)
            else:
                print("运行完成！")                

    def reset_progress_bar(self):
        self.progressBar.setValue(0)

    def on_data_dir_clicked(self):
        folder_path = QFileDialog.getExistingDirectory(None, "选择数据目录", "")
        self.inputLineEdit.setText(str(folder_path))
        self.settings.setValue('data_path', str(folder_path))

    def on_data_config_clicked(self):
        config_path, _ = QFileDialog.getOpenFileName(None, "选择配置文件", self.configLineEdit.text(), "txt file(*.txt)")
        self.configLineEdit.setText(str(config_path))
        self.settings.setValue('config_path', str(config_path))

    def on_data_log_clicked(self):
        log_path, _ = QFileDialog.getSaveFileName(None, "保存日志文件", self.logLineEdit.text(), "log file(*.txt)")
        self.logLineEdit.setText(str(log_path))
        self.settings.setValue('log_path', str(log_path))

    def on_data_op_clicked(self):
        folder_path = QFileDialog.getExistingDirectory(None, "选择处理结果目录", "")
        self.outputLineEdit.setText(str(folder_path))
        self.settings.setValue('op_path', str(folder_path))

    def modify_data_optimization(self, out_dir, data_path, data_type):
        result_str = []
        if data_type == 0:
            vector_files = glob.glob(os.path.join(out_dir, data_path, '*.shp'))
            for vector_file in vector_files:
                layer_name = splitext(split(vector_file)[1])[0]
                layer_splits = layer_name.split('_')

                if len(layer_splits) < 2:
                    result_str.append([0, vector_file, layer_name, []])
                    continue
                
                compare_config_name = ''
                is_begin = False
                for i in range(1, len(layer_splits)):
                    if is_begin == False and len(layer_splits[i]) == 0:
                        continue
                    is_begin = True
                    if len(compare_config_name) == 0:
                        compare_config_name = layer_splits[i]
                        continue
                    compare_config_name = compare_config_name + '_' + layer_splits[i]
                
                if compare_config_name not in self.config_data:
                    result_str.append([0, vector_file, layer_name, []])
                    continue

                vector_layer = QgsVectorLayer(vector_file)
                if vector_layer.isValid() == False:
                    result_str.append([0, vector_file, layer_name, []])
                    continue

                vector_layer.startEditing()
                vector_fields = vector_layer.fields()
                fields_array = self.config_data[compare_config_name]
                modify_data = []

                exist_fields = []
                for field_array in fields_array:
                    if len(field_array) < 2:
                        continue
                    exist_field_index = vector_fields.indexOf(field_array[0])
                    if exist_field_index != -1:
                        exist_fields.append(exist_field_index)

                for i in range(len(vector_fields)-1, -1, -1):
                    if vector_fields[i].name() == 'fid' or vector_fields[i].name() == 'OBJECTID' or vector_fields[i].name() == 'Shape_Length' or vector_fields[i].name() == 'Shape_Area':
                        continue
                    if i not in exist_fields:
                        vector_layer.deleteAttribute(i)
                        modify_data.append([2, vector_fields[i].name(), []])
                vector_layer.updateFields()

                for field_array in fields_array:
                    if len(field_array) < 2:
                        continue

                    if field_array[1] == QVariant.Invalid:
                        modify_data.append([4, field_array[0], '无效的字段类型'])
                        continue

                    field_index = vector_fields.indexOf(field_array[0])
                    error_data = []

                    layer_feature = QgsFeature()
                    current_field_name = field_array[0]
                    if field_index != -1:
                        #找到了则判断type是不是一样,一样就不做修改了
                        if field_array[1] != vector_fields[field_index].type():

                            #String转real, String转integer, real转integer
                            if vector_fields[field_index].type() == QVariant.String and field_array[1] == QVariant.Int:
                                modify_data.append([4, field_array[0], '字段不能从string转int'])
                                continue

                            if vector_fields[field_index].type() == QVariant.String and field_array[1] == QVariant.Double:
                                modify_data.append([4, field_array[0], '字段不能从string转real'])
                                continue

                            if vector_fields[field_index].type() == QVariant.Double and field_array[1] == QVariant.Int:
                                modify_data.append([4, field_array[0], '字段不能从real转int'])
                                continue                  

                            tmp_add_field_name = current_field_name + 'J'
                            tmp_field_index = vector_fields.indexOf(tmp_add_field_name)
                            if len(field_array) >=3:
                                if field_array[1] == QVariant.Int:
                                    len_value = int(field_array[2])
                                    vector_layer.addAttribute(QgsField(tmp_add_field_name, field_array[1], len=len_value))
                                elif field_array[1] == QVariant.Double:
                                    dec_value = int(field_array[2])
                                    vector_layer.addAttribute(QgsField(tmp_add_field_name, field_array[1],prec=dec_value, len=20))
                                else:
                                    len_value = int(field_array[2])
                                    vector_layer.addAttribute(QgsField(tmp_add_field_name, field_array[1],len=len_value))
                            else:
                                if field_array[1] == QVariant.Int:
                                    vector_layer.addAttribute(QgsField(tmp_add_field_name, field_array[1]))
                                elif field_array[1] == QVariant.Double:
                                    vector_layer.addAttribute(QgsField(tmp_add_field_name, field_array[1],prec=8, len=20))
                                else:
                                    vector_layer.addAttribute(QgsField(tmp_add_field_name, field_array[1],len=20)) 
                            
                            vector_layer.updateFields()
                            it = vector_layer.getFeatures()
                            while it.nextFeature(layer_feature):
                                feature = layer_feature
                                value = feature[current_field_name]
                                try:
                                    if field_array[1] == QVariant.Int:
                                        feature[tmp_add_field_name] = int(value)
                                    elif field_array[1] == QVariant.Double:
                                        feature[tmp_add_field_name] = Decimal(value)
                                    else:
                                        feature[tmp_add_field_name] = str(value)
                                    vector_layer.updateFeature(feature)
                                except ValueError:
                                    error_data.append(feature.id())
                                    continue
                                
                            # 更新字段类型

                            field_index = vector_layer.fields().indexOf(field_array[0])
                            vector_layer.deleteAttribute(field_index)
                            #vector_layer.updateFields()
                            tmp_field_index = vector_layer.fields().indexOf(tmp_add_field_name)
                            vector_layer.renameAttribute(tmp_field_index, field_array[0])
                            vector_layer.updateFields()

                            modify_data.append([0, current_field_name, error_data])
                        elif field_array[1] == vector_fields[field_index].type() and len(field_array) >=3:
                            #如果长度不相等则改变长度
                            len_value = int(field_array[2])
                            if vector_fields[field_index].length() != len_value:
                                tmp_add_field_name = current_field_name + 'J'
                                if field_array[1] == QVariant.Int:
                                    vector_layer.addAttribute(QgsField(tmp_add_field_name, field_array[1], len=len_value))
                                elif field_array[1] == QVariant.Double:
                                    vector_layer.addAttribute(QgsField(tmp_add_field_name, field_array[1],prec=len_value, len=20))
                                else:
                                    vector_layer.addAttribute(QgsField(tmp_add_field_name, field_array[1],len=len_value))
                                vector_layer.updateFields()
                                it = vector_layer.getFeatures()
                                while it.nextFeature(layer_feature):
                                    feature = layer_feature
                                    value = feature[current_field_name]
                                    try:
                                        if field_array[1] == QVariant.Int:
                                            feature[tmp_add_field_name] = int(value)
                                        elif field_array[1] == QVariant.Double:
                                            feature[tmp_add_field_name] = Decimal(value)
                                        else:
                                            feature[tmp_add_field_name] = str(value)
                                        vector_layer.updateFeature(feature)
                                    except ValueError:
                                        error_data.append(feature.id())
                                        continue
                                    
                                # 更新字段类型
                                field_index = vector_layer.fields().indexOf(field_array[0])
                                vector_layer.deleteAttribute(field_index)
                                #vector_layer.updateFields()
                                tmp_field_index = vector_layer.fields().indexOf(tmp_add_field_name)
                                vector_layer.renameAttribute(tmp_field_index, field_array[0])
                                vector_layer.updateFields()

                                modify_data.append([3, current_field_name, error_data])
                    else:
                        if len(field_array) >=3:
                            if field_array[1] == QVariant.Int:
                                len_value = int(field_array[2])
                                vector_layer.addAttribute(QgsField(current_field_name, field_array[1], len=len_value))
                            elif field_array[1] == QVariant.Double:
                                dec_value = int(field_array[2])
                                vector_layer.addAttribute(QgsField(current_field_name, field_array[1],prec=dec_value, len=20))
                            else:
                                len_value = int(field_array[2])
                                vector_layer.addAttribute(QgsField(current_field_name, field_array[1],len=len_value))
                        else:
                            if field_array[1] == QVariant.Int:
                                vector_layer.addAttribute(QgsField(current_field_name, field_array[1]))
                            elif field_array[1] == QVariant.Double:
                                vector_layer.addAttribute(QgsField(current_field_name, field_array[1],prec=8, len=20))
                            else:
                                vector_layer.addAttribute(QgsField(current_field_name, field_array[1],len=20))
                        vector_layer.updateFields()
                        modify_data.append([1, current_field_name, []])

                vector_layer.commitChanges()
                result_str.append([0, vector_file, layer_name, modify_data])
            return result_str
        
        gpkg_layers = self.get_Gpkg_Layers(data_path)
        for vector_layer in gpkg_layers:
            layer_name = vector_layer.name()
            layer_splits = layer_name.split('_')
            if len(layer_splits) < 2:
                result_str.append([0, vector_layer.source(), layer_name, []])
                continue

            compare_config_name = ''
            is_begin = False
            for i in range(1, len(layer_splits)):
                if len(layer_splits[i]) == 0 and is_begin == False:
                    continue
                is_begin = True
                if len(compare_config_name) == 0:
                    compare_config_name = layer_splits[i]
                    continue
                compare_config_name = compare_config_name + '_' + layer_splits[i]
            if compare_config_name not in self.config_data:
                result_str.append([0, vector_layer.source(), layer_name, []])
                continue
            
            if vector_layer.isValid() == False:
                result_str.append([0, vector_layer.source(), layer_name, []])
                continue
            
            vector_layer.startEditing()
            fields_array = self.config_data[compare_config_name]

            modify_data = []

            exist_fields = []
            vector_fields = vector_layer.fields()
            for field_array in fields_array:
                if len(field_array) < 2:
                    continue

                exist_field_index = vector_fields.indexOf(field_array[0])
                if exist_field_index != -1:
                    exist_fields.append(exist_field_index)

            for i in range(len(vector_fields)-1, -1, -1):
                if vector_fields[i].name() == 'fid' or vector_fields[i].name() == 'OBJECTID' or vector_fields[i].name() == 'Shape_Length' or vector_fields[i].name() == 'Shape_Area':
                    continue
                if i not in exist_fields:
                    vector_layer.deleteAttribute(i)
                    modify_data.append([2, vector_fields[i].name(), []])
            vector_layer.updateFields()

            for field_array in fields_array:
                if len(field_array) < 2:
                    continue

                if field_array[1] == QVariant.Invalid:
                    modify_data.append([4, field_array[0], '无效的字段类型'])
                    continue

                field_index = vector_fields.indexOf(field_array[0])
                current_field_name = field_array[0]
                layer_feature = QgsFeature()
                error_data = []

                if field_index != -1:
                    #找到了则判断type是不是一样,一样就不做修改了
                    if field_array[1] != vector_fields[field_index].type():
                        #String转real, String转integer, real转integer
                        if vector_fields[field_index].type() == QVariant.String and field_array[1] == QVariant.Int:
                            modify_data.append([4, field_array[0], '字段不能从string转int'])
                            continue

                        if vector_fields[field_index].type() == QVariant.String and field_array[1] == QVariant.Double:
                            modify_data.append([4, field_array[0], '字段不能从string转real'])
                            continue

                        if vector_fields[field_index].type() == QVariant.Double and field_array[1] == QVariant.Int:
                            modify_data.append([4, field_array[0], '字段不能从real转int'])
                            continue 

                        tmp_add_field_name = current_field_name + 'J'
                        if len(field_array) >= 3:
                            if field_array[1] == QVariant.Int:
                                len_value = int(field_array[2])
                                vector_layer.addAttribute(QgsField(tmp_add_field_name, field_array[1], len = len_value))
                            elif field_array[1] == QVariant.Double:
                                dec_value = int(field_array[2])
                                vector_layer.addAttribute(QgsField(tmp_add_field_name, field_array[1],prec=dec_value, len=20))
                            else:
                                len_value = int(field_array[2])
                                vector_layer.addAttribute(QgsField(tmp_add_field_name, field_array[1],len=len_value))
                        else:
                            if field_array[1] == QVariant.Int:
                                vector_layer.addAttribute(QgsField(tmp_add_field_name, field_array[1]))
                            elif field_array[1] == QVariant.Double:
                                vector_layer.addAttribute(QgsField(tmp_add_field_name, field_array[1],prec=8, len=20))
                            else:
                                vector_layer.addAttribute(QgsField(tmp_add_field_name, field_array[1],len=20)) 
                        vector_layer.updateFields()
                        it = vector_layer.getFeatures()
                        while it.nextFeature(layer_feature):
                            feature = layer_feature
                            value = feature[current_field_name]
                            try:
                                if field_array[1] == QVariant.Int:
                                    feature[tmp_add_field_name] = int(value)
                                elif field_array[1] == QVariant.Double:
                                    feature[tmp_add_field_name] = Decimal(value)
                                else:
                                    feature[tmp_add_field_name] = str(value)
                                vector_layer.updateFeature(feature)
                            except ValueError:
                                error_data.append(feature.id())
                                continue
                            
                        # 更新字段类型
                        field_index = vector_layer.fields().indexOf(field_array[0])
                        
                        vector_layer.deleteAttribute(field_index)
                        #vector_layer.updateFields()
                        tmp_field_index = vector_layer.fields().indexOf(tmp_add_field_name)
                        vector_layer.renameAttribute(tmp_field_index, field_array[0])
                        vector_layer.updateFields()
                        modify_data.append([0, current_field_name, error_data])
                    elif field_array[1] == vector_fields[field_index].type() and len(field_array) >=3:
                            #如果长度不相等则改变长度
                            len_value = int(field_array[2])
                            if vector_fields[field_index].length() != len_value:
                                tmp_add_field_name = current_field_name + 'J'
                                if field_array[1] == QVariant.Int:
                                    vector_layer.addAttribute(QgsField(tmp_add_field_name, field_array[1], len=len_value))
                                elif field_array[1] == QVariant.Double:
                                    vector_layer.addAttribute(QgsField(tmp_add_field_name, field_array[1],prec=len_value, len=20))
                                else:
                                    vector_layer.addAttribute(QgsField(tmp_add_field_name, field_array[1],len=len_value))
                                vector_layer.updateFields()
                                it = vector_layer.getFeatures()
                                while it.nextFeature(layer_feature):
                                    feature = layer_feature
                                    value = feature[current_field_name]
                                    try:
                                        if field_array[1] == QVariant.Int:
                                            feature[tmp_add_field_name] = int(value)
                                        elif field_array[1] == QVariant.Double:
                                            feature[tmp_add_field_name] = Decimal(value)
                                        else:
                                            feature[tmp_add_field_name] = str(value)
                                        vector_layer.updateFeature(feature)
                                    except ValueError:
                                        error_data.append(feature.id())
                                        continue
                                    
                                # 更新字段类型
                                field_index = vector_layer.fields().indexOf(field_array[0])
                                vector_layer.deleteAttribute(field_index)
                                #vector_layer.updateFields()
                                tmp_field_index = vector_layer.fields().indexOf(tmp_add_field_name)
                                vector_layer.renameAttribute(tmp_field_index, field_array[0])
                                vector_layer.updateFields()

                                modify_data.append([3, current_field_name, error_data])
                else:
                    if len(field_array) >=3:
                        if field_array[1] == QVariant.Int:
                            len_value = int(field_array[2])
                            vector_layer.addAttribute(QgsField(current_field_name, field_array[1],len=len_value))
                        elif field_array[1] == QVariant.Double:
                            dec_value = int(field_array[2])
                            vector_layer.addAttribute(QgsField(current_field_name, field_array[1],prec=dec_value, len=20))
                        else:
                            len_value = int(field_array[2])
                            vector_layer.addAttribute(QgsField(current_field_name, field_array[1],len=len_value))
                    else:
                        if field_array[1] == QVariant.Int:
                            vector_layer.addAttribute(QgsField(current_field_name, field_array[1]))
                        elif field_array[1] == QVariant.Double:
                            vector_layer.addAttribute(QgsField(current_field_name, field_array[1],prec=8, len=20))
                        else:
                            vector_layer.addAttribute(QgsField(current_field_name, field_array[1],len=20))
                    modify_data.append([1, current_field_name, []])
                        
                    vector_layer.updateFields()

            vector_layer.commitChanges()
            result_str.append([1, vector_layer.source(), layer_name, modify_data])
        return result_str
    
    def get_Gpkg_Layers(self, gpkg_path):
        layer_list = []
        driver = ogr.GetDriverByName('GPKG')
        gpkg_source = driver.Open(gpkg_path, 0)  # 0 表示只读模式
        if gpkg_source is None:
            return layer_list
        
        # 获取所有图层名称
        layers = gpkg_source.GetLayerCount()  # 获取图层数量
        layer_names = [gpkg_source.GetLayerByIndex(i).GetName() for i in range(layers)]
        for name in layer_names:
            uri = f'{gpkg_path}|layername={name}'
            layer = QgsVectorLayer(uri, name, 'ogr')
            if layer.isValid() and (layer.geometryType() == QgsWkbTypes.PointGeometry or layer.geometryType() == QgsWkbTypes.LineGeometry or layer.geometryType() == QgsWkbTypes.PolygonGeometry):
                layer_list.append(layer)
        return layer_list

    def on_process_button_clicked(self):
        if len(self.inputLineEdit.text()) == 0:
            if self.showDlg:
                QMessageBox.warning(self, '警告', '数据目录不能为空')
            return
        
        if len(self.configLineEdit.text()) == 0:
            if self.showDlg:
                QMessageBox.warning(self, '警告', '配置文件不能为空')
            return
             
        if len(self.logLineEdit.text()) == 0:
            if self.showDlg:
                QMessageBox.warning(self, '警告', '日志文件不能为空')
            return
            
        if len(self.outputLineEdit.text()) == 0:
            if self.showDlg:
                QMessageBox.warning(self, '警告', '处理结果目录不能为空')
            return
        
        dataType = 0 if self.shpRadioButton.isChecked() else 1
        self.settings.setValue('data_type', dataType)

        self.progressBar.setValue(0)
        if self.showDlg:
            QApplication.processEvents()

        #读取配置文件
        self.config_data = {}
        current_layer_name = ''
        current_data = []
        with open(self.configLineEdit.text(), 'r') as file:
            # 逐行读取
            for line in file:
                line_str = line.strip()
                if len(line_str) == 0:
                    continue
                config_fields = line_str.split(',')
                if len(config_fields) == 1:
                    if len(current_layer_name) != 0:
                        self.config_data[current_layer_name] = current_data
                    current_layer_name = config_fields[0].strip()
                    current_data = []
                    continue
                
                config_field_type = config_fields[1].strip().lower()

                #integer 0 real 1 str 2
                if config_field_type == 'integer':
                    #如果没有设置，后面新建字段的时候就按默认来,目前设置成0
                    data_len = 0
                    if len(config_fields) >= 3:
                       data_len = int(config_fields[2])
                    current_data.append([config_fields[0], QVariant.Int, data_len])
                elif config_field_type == 'real':
                    data_len = 0
                    if len(config_fields) >= 3:
                       data_len = int(config_fields[2])
                    current_data.append([config_fields[0], QVariant.Double, data_len])
                elif config_field_type == 'string':
                    data_len = 0
                    if len(config_fields) >= 3:
                       data_len = int(config_fields[2])
                    current_data.append([config_fields[0], QVariant.String, data_len])
                else:
                    data_len = 0
                    if len(config_fields) >= 3:
                       data_len = int(config_fields[2])
                    current_data.append([config_fields[0], QVariant.Invalid, data_len])                   

            if len(current_data) != 0:
                self.config_data[current_layer_name] = current_data        
            file.close()

        if os.path.exists(self.outputLineEdit.text()):
            shutil.rmtree(self.outputLineEdit.text())  # 删除目标文件夹
        shutil.copytree(self.inputLineEdit.text(), self.outputLineEdit.text())
        self.progressBar.setValue(10)
        if self.showDlg:
            QApplication.processEvents()

        outputPaths = []
        outDir = self.outputLineEdit.text()
        if self.shpRadioButton.isChecked():
            outputPaths = os.listdir(outDir)
        else:
            outputPaths = glob.glob(os.path.join(outDir, '*.gpkg'))
        if len(outputPaths) == 0:
            if self.showDlg:
                QMessageBox.warning(self, '警告', '数据目录为空')
                self.progressBar.setValue(100)
                QApplication.processEvents()
            return
        
        cur_step = 80.0 / len(outputPaths)
        cur_future_prog = 0


        result_log = []
        for i in range(len(outputPaths)):
        #with concurrent.futures.ThreadPoolExecutor(max_workers=self.max_thread_num) as executor:
            # 提交任务到线程池中执行
            #optimization_to_task = { executor.submit(self.modify_data_optimization, self.outputLineEdit.text(), outputPaths[n], dataType ): n for n in range(len(outputPaths)) }
            
            # 等待所有任务完成

            #for future_data in concurrent.futures.as_completed(optimization_to_task):
                #result_log = result_log + future_data.result()
            result_log = result_log + self.modify_data_optimization(self.outputLineEdit.text(), outputPaths[i], dataType)
            cur_future_prog = cur_future_prog + 1
            self.progress_signal.emit((int)(cur_step * cur_future_prog + 10), "")
            
        log_file = open(self.logLineEdit.text(),"w")

        for i in range(len(result_log)):
            write_str = ''
            i_file = result_log[i]
            if i_file[0] == 0:
                write_str = write_str + 'shp文件[' + i_file[1] + ']:\n'
            else:
                write_str = write_str + 'gpkg文件[' + i_file[1] + '] 图层名为[' + i_file[2] + ']:\n'

            data_file = i_file[3]
            log_len = len(data_file)
            write_str = write_str + '增加的字段:'
            for j in range(log_len):
                if data_file[j][0] != 1:
                    continue
                write_str = write_str + ' ' + data_file[j][1] + ' '
            write_str = write_str + '\n'

            write_str = write_str + '删除的字段:'
            for j in range(log_len):
                if data_file[j][0] != 2:
                    continue
                write_str = write_str + ' ' + data_file[j][1] + ' '
            write_str = write_str + '\n'

            write_str = write_str + '修改类型的字段:'
            for j in range(log_len):
                if data_file[j][0] != 0:
                    continue
                write_str = write_str + ' ' + data_file[j][1] + ' '
            write_str = write_str + '\n'

            write_str = write_str + '修改长度的字段:'
            for j in range(log_len):
                if data_file[j][0] != 3:
                    continue
                write_str = write_str + ' ' + data_file[j][1] + ' '
            write_str = write_str + '\n'

            write_str = write_str + '无效的字段:'
            for j in range(log_len):
                if data_file[j][0] != 4:
                    continue
                write_str = write_str + ' ' + data_file[j][1] + ':' + data_file[j][2] + ' '
            write_str = write_str + '\n\n\n'
            log_file.write(write_str)
        log_file.close()  
        self.progress_signal.emit(100, "完成")

    def process(self, inputPath, configPath, logPath, outPutPath, dataType):
        if len(inputPath) == 0:
            if self.showDlg:
                QMessageBox.warning(self, '警告', '数据目录不能为空')
            return
        
        if len(configPath) == 0:
            if self.showDlg:
                QMessageBox.warning(self, '警告', '配置文件不能为空')
            return
                
        if len(logPath) == 0:
            if self.showDlg:
                QMessageBox.warning(self, '警告', '日志文件不能为空')
            return
            
        if len(outPutPath) == 0:
            if self.showDlg:
                QMessageBox.warning(self, '警告', '处理结果目录不能为空')
            return
        
        if self.showDlg:   
            self.progressBar.setValue(0)
            QApplication.processEvents()

        #读取配置文件
        self.config_data = {}
        current_layer_name = ''
        current_data = []
        with open(configPath, 'r', encoding='utf-8') as file:
            # 逐行读取
            for line in file:
                line_str = line.strip()
                if len(line_str) == 0:
                    continue
                config_fields = line_str.split(',')
                if len(config_fields) == 1:
                    if len(current_layer_name) != 0:
                        self.config_data[current_layer_name] = current_data
                    current_layer_name = config_fields[0].strip()
                    current_data = []
                    continue
                
                config_field_type = config_fields[1].strip().lower()

                #integer 0 real 1 str 2
                if config_field_type == 'integer':
                    #如果没有设置，后面新建字段的时候就按默认来,目前设置成0
                    data_len = 0
                    if len(config_fields) >= 3:
                        data_len = int(config_fields[2])
                    current_data.append([config_fields[0], QVariant.Int, data_len])
                elif config_field_type == 'real':
                    data_len = 0
                    if len(config_fields) >= 3:
                        data_len = int(config_fields[2])
                    current_data.append([config_fields[0], QVariant.Double, data_len])
                elif config_field_type == 'string':
                    data_len = 0
                    if len(config_fields) >= 3:
                       data_len = int(config_fields[2])
                    current_data.append([config_fields[0], QVariant.String, data_len])
                else:
                    data_len = 0
                    if len(config_fields) >= 3:
                       data_len = int(config_fields[2])
                    current_data.append([config_fields[0], QVariant.Invalid, data_len])     

            if len(current_data) != 0:
                self.config_data[current_layer_name] = current_data        
            file.close()

        if os.path.exists(outPutPath):
            shutil.rmtree(outPutPath)  # 删除目标文件夹
        shutil.copytree(inputPath, outPutPath)

        if self.showDlg:
            self.progressBar.setValue(10)
            QApplication.processEvents()

        outputPaths = []
        outDir = outPutPath
        if dataType == 0:
            outputPaths = os.listdir(outDir)
        else:
            outputPaths = glob.glob(os.path.join(outDir, '*.gpkg'))
            # outputlayers = []
            # for outputPath in outputPaths:
            #     layers = self.get_Gpkg_Layers(outputPath)
            #     outputlayers = outputlayers + layers
            #     outputPaths = outputlayers
        if len(outputPaths) == 0:
            if self.showDlg:
                QMessageBox.warning(self, '警告', '数据目录为空')
                self.progressBar.setValue(100)
                QApplication.processEvents()
            return
        
        cur_step = 80.0 / len(outputPaths)
        cur_future_prog = 0
        with concurrent.futures.ThreadPoolExecutor(max_workers=self.max_thread_num) as executor:
            # 提交任务到线程池中执行
            optimization_to_task = { executor.submit(self.modify_data_optimization, outPutPath, outputPaths[n], dataType ): n for n in range(len(outputPaths)) }
            
            # 等待所有任务完成
            result_log = []
            for future_data in concurrent.futures.as_completed(optimization_to_task):
                result_log = result_log + future_data.result()
                cur_future_prog = cur_future_prog + 1
                self.progress_signal.emit((int)(cur_step * cur_future_prog + 10), "")
            
            log_file = open(logPath,"w")

            for i in range(len(result_log)):
                write_str = ''
                i_file = result_log[i]
                if i_file[0] == 0:
                    write_str = write_str + 'shp文件[' + i_file[1] + ']:\n'
                else:
                    write_str = write_str + 'gpkg文件[' + i_file[1] + '] 图层名为[' + i_file[2] + ']:\n'

                data_file = i_file[3]
                log_len = len(data_file)
                write_str = write_str + '增加的字段:'
                for j in range(log_len):
                    if data_file[j][0] != 1:
                        continue
                    write_str = write_str + ' ' + data_file[j][1] + ' '
                write_str = write_str + '\n'

                write_str = write_str + '删除的字段:'
                for j in range(log_len):
                    if data_file[j][0] != 2:
                        continue
                    write_str = write_str + ' ' + data_file[j][1] + ' '
                write_str = write_str + '\n'

                write_str = write_str + '修改类型的字段:'
                for j in range(log_len):
                    if data_file[j][0] != 0:
                        continue
                    write_str = write_str + ' ' + data_file[j][1] + ' '
                write_str = write_str + '\n'

                write_str = write_str + '修改长度的字段:'
                for j in range(log_len):
                    if data_file[j][0] != 3:
                        continue
                    write_str = write_str + ' ' + data_file[j][1] + ' '
                write_str = write_str + '\n'

                write_str = write_str + '无效的字段:'
                for j in range(log_len):
                    if data_file[j][0] != 4:
                        continue
                    write_str = write_str + ' ' + data_file[j][1] + ':' + data_file[j][2] + ' '
                write_str = write_str + '\n\n\n'
                log_file.write(write_str)
            log_file.close()  
            self.progress_signal.emit(100, "完成")

    def on_close_button_clicked(self):
        self.close()