# -*- coding: utf-8 -*-
"""
/***************************************************************************
dataEncodeConvertDialog
                                 A QGIS plugin
 DataEncodeConvert
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-25
        git sha              : $Format:%H$
        copyright            : (C) 2024 by 星球
        email                : 星球
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import glob
import shutil
from qgis.PyQt import uic, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox, QApplication
from PyQt5.QtCore import QThread, pyqtSignal, QVariant, QSettings
from os.path import split, splitext
from pathlib import Path
from qgis.core import QgsVectorLayer, QgsProviderRegistry, QgsVectorFileWriter, QgsProject, QgsCoordinateTransform, QgsMessageLog, Qgis
# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'dataEncodeConvert_dialog_base.ui'))


class dataEncodeConvertDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None, showDlg=True):
        """Constructor."""
        super(dataEncodeConvertDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.showDlg = showDlg
        #浏览数据目录
        self.inputPushButton.clicked.connect(self.on_data_dir_clicked)
        #浏览处理结果目录
        self.outputPushButton.clicked.connect(self.on_data_op_clicked)
        
        #开始转换处理
        self.convertButton.clicked.connect(self.on_process_button_clicked)

        #关闭对话框
        self.closeButton.clicked.connect(self.on_close_button_clicked)

        self.settings = QSettings('XingqiuCompany', 'dataEncodeConvert')
        self.inputLineEdit.setText(self.settings.value('data_path', ''))
        self.outputLineEdit.setText(self.settings.value('op_path', ''))

        dataType = self.settings.value('data_type', 0, type=int)
        if dataType == 0:
            self.shpRadioButton.setChecked(True)
        else:
            self.gpkgRadioButton.setChecked(True)

    def on_data_dir_clicked(self):
        folder_path = QFileDialog.getExistingDirectory(None, "选择数据目录", "")
        self.inputLineEdit.setText(str(folder_path))
        self.settings.setValue('data_path', str(folder_path))

    def on_data_op_clicked(self):
        folder_path = QFileDialog.getExistingDirectory(None, "选择处理结果目录", "")
        self.outputLineEdit.setText(str(folder_path))
        self.settings.setValue('op_path', str(folder_path))

    def reset_progress_bar(self):
        self.progressBar.setValue(0)

    def convert_shp_dir(self, src_dir, dst_dir, suffixName):
        if not os.path.exists(dst_dir):
            os.makedirs(dst_dir)  # 如果目标目录不存在，则创建它
    
        for item in os.listdir(src_dir):
            src_path = os.path.join(src_dir, item)
            dest_path = os.path.join(dst_dir, item)
            
            if os.path.isdir(src_path):
                # 如果是目录，递归复制
                self.convert_shp_dir(src_path, dest_path, suffixName)
            else:
                options = QgsVectorFileWriter.SaveVectorOptions()
                options.fileEncoding = 'UTF-8'
                options.actionOnExistingFile = QgsVectorFileWriter.ActionOnExistingFile.CreateOrOverwriteFile
                options.driverName = 'ESRI Shapefile'
                vector_file_extension = Path(src_path).suffix.lower()
                if vector_file_extension != suffixName:
                    continue
                
                vector_layer = QgsVectorLayer(src_path)
                if vector_layer.isValid() == False:
                    continue
                ct = QgsCoordinateTransform(vector_layer.crs(), vector_layer.crs(), vector_layer.transformContext())
                options.ct = ct
                QgsVectorFileWriter.writeAsVectorFormatV3(vector_layer, dest_path, vector_layer.transformContext(), options)             

    def process(self, inputPath, outPath, dataType):
        if len(inputPath) == 0:
            if self.showDlg:
                QMessageBox.warning(self, '警告', '数据目录不能为空')
            return
        
        if len(outPath) == 0:
            if self.showDlg:
                QMessageBox.warning(self, '警告', '处理结果目录不能为空')
            return
        
        self.progressBar.setValue(0)        
        if self.showDlg:
            QApplication.processEvents()
        else:
            print('开始转换')
        
        # filterName = "*.shp" if self.shpRadioButton.isChecked() else "*.gpkg"
        list_dir = os.listdir(inputPath)
        # vector_files = glob.glob(os.path.join(self.inputLineEdit.text(), filterName))
        if len(list_dir) == 0:
            if self.showDlg:
                QMessageBox.information(None, '提示', '没有找到需要进行转换的文件')
            return
        
        prog = 100.0 / len(list_dir)
        idx = 0
        if dataType == 0:
            suffixName = ".shp"
            options = QgsVectorFileWriter.SaveVectorOptions()
            options.fileEncoding = 'UTF-8'
            options.actionOnExistingFile = QgsVectorFileWriter.ActionOnExistingFile.CreateOrOverwriteFile
            options.driverName = 'ESRI Shapefile'

            list_dir = os.listdir(inputPath)
            for item_path in list_dir:
                src_path = os.path.join(inputPath, item_path)
                dest_path = os.path.join(outPath, item_path)
                
                if os.path.isdir(src_path):
                    self.convert_shp_dir(src_path, dest_path, suffixName)
                else:
                    vector_file_extension = Path(src_path).suffix.lower()
                    if vector_file_extension != suffixName:
                        idx = idx + 1
                        self.progressBar.setValue((int)(idx * prog))
                        continue
                    vector_layer = QgsVectorLayer(src_path)
                    if vector_layer.isValid() == False:
                        idx = idx + 1
                        self.progressBar.setValue((int)(idx * prog))
                        continue
                    ct = QgsCoordinateTransform(vector_layer.crs(), vector_layer.crs(), vector_layer.transformContext())
                    options.ct = ct
                    QgsVectorFileWriter.writeAsVectorFormatV3(vector_layer, dest_path, vector_layer.transformContext(), options)             
                idx = idx + 1
                self.progressBar.setValue((int)(idx * prog))
                if self.showDlg:
                    QApplication.processEvents()
                else:
                    print('转换进度:'+ str((int)(idx * prog)) + '%')   
        else:
            #gpkg文件只能为utf8，直接复制源文件
            if os.path.exists(outPath):
                shutil.rmtree(outPath)  # 删除目标文件夹
            shutil.copytree(inputPath, outPath)

        if self.showDlg:
            self.progressBar.setValue(100)
            QApplication.processEvents()
            QMessageBox.information(None, '提示', '完成')
        else:
            print("转换完成!")             
        # self.processCls = processData()
        # self.processCls.setParam(self.data_dir_edit.text(), self.data_check_edit.text(), self.data_op_edit.text(), self.progressBar)
        # #self.thread.progress_signal.connect(self.progressBar.setValue)
        # self.processCls.process()
        # folder_path = QFileDialog.getExistingDirectory(None, "选择数据目录", "")
        # self.dataLineEdit.setText(str(folder_path))
        # self.settings.setValue('data_path', str(folder_path))


    def on_process_button_clicked(self):
        if len(self.inputLineEdit.text()) == 0:
            if self.showDlg:
                QMessageBox.warning(self, '警告', '数据目录不能为空')
            return
        
        if len(self.outputLineEdit.text()) == 0:
            if self.showDlg:
                QMessageBox.warning(self, '警告', '处理结果目录不能为空')
            return
        
        self.settings.setValue('data_type', 0 if self.shpRadioButton.isChecked() else 1)

        
        self.progressBar.setValue(0)
        if self.showDlg:
            QApplication.processEvents()
        
        # filterName = "*.shp" if self.shpRadioButton.isChecked() else "*.gpkg"
        list_dir = os.listdir(self.inputLineEdit.text())
        # vector_files = glob.glob(os.path.join(self.inputLineEdit.text(), filterName))
        if len(list_dir) == 0:
            if self.showDlg:
                QMessageBox.information(None, '提示', '没有找到需要进行转换的文件')
            return
        
        prog = 100.0 / len(list_dir)
        idx = 0
        if self.shpRadioButton.isChecked():
            suffixName = ".shp" if self.shpRadioButton.isChecked() else ".gpkg"
            options = QgsVectorFileWriter.SaveVectorOptions()
            options.fileEncoding = 'UTF-8'
            options.actionOnExistingFile = QgsVectorFileWriter.ActionOnExistingFile.CreateOrOverwriteFile
            options.driverName = 'ESRI Shapefile'

            list_dir = os.listdir(self.inputLineEdit.text())
            for item_path in list_dir:
                src_path = os.path.join(self.inputLineEdit.text(), item_path)
                dest_path = os.path.join(self.outputLineEdit.text(), item_path)
                
                if os.path.isdir(src_path):
                    self.convert_shp_dir(src_path, dest_path, suffixName)
                else:
                    vector_file_extension = Path(src_path).suffix.lower()
                    if vector_file_extension != suffixName:
                        continue
                    vector_layer = QgsVectorLayer(src_path)
                    if vector_layer.isValid() == False:
                        continue
                    ct = QgsCoordinateTransform(vector_layer.crs(), vector_layer.crs(), vector_layer.transformContext())
                    options.ct = ct
                    QgsVectorFileWriter.writeAsVectorFormatV3(vector_layer, dest_path, vector_layer.transformContext(), options)             
                idx = idx + 1
                self.progressBar.setValue((int)(idx * prog))
                if self.showDlg:
                    QApplication.processEvents()    
        else:
            #gpkg文件只能为utf8，直接复制源文件
            if os.path.exists(self.outputLineEdit.text()):
                shutil.rmtree(self.outputLineEdit.text())  # 删除目标文件夹
            shutil.copytree(self.inputLineEdit.text(), self.outputLineEdit.text())

        if self.showDlg:
            self.progressBar.setValue(100)
            QApplication.processEvents()
            QMessageBox.information(None, '提示', '完成')
        else:
            print("转换完成!")             
        # self.processCls = processData()
        # self.processCls.setParam(self.data_dir_edit.text(), self.data_check_edit.text(), self.data_op_edit.text(), self.progressBar)
        # #self.thread.progress_signal.connect(self.progressBar.setValue)
        # self.processCls.process()
        # folder_path = QFileDialog.getExistingDirectory(None, "选择数据目录", "")
        # self.dataLineEdit.setText(str(folder_path))
        # self.settings.setValue('data_path', str(folder_path))

    def on_close_button_clicked(self):
        self.close()