# -*- coding: utf-8 -*-
"""
/***************************************************************************
 dataFormatConvertDialog
                                 A QGIS plugin
 dataFormatConvert
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-01
        git sha              : $Format:%H$
        copyright            : (C) 2025 by xing qiu
        email                : xing qiu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import glob
import shutil
from qgis.PyQt import uic, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox, QApplication
from PyQt5.QtCore import QThread, pyqtSignal, QVariant, QSettings
from os.path import split, splitext
import platform
from qgis.core import QgsVectorLayer, QgsProviderRegistry, QgsVectorFileWriter, QgsProject, QgsCoordinateTransform
import subprocess
import platform

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'dataFormatConvert_dialog_base.ui'))


class dataFormatConvertDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None, showDlg=True):
        """Constructor."""
        super(dataFormatConvertDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.showDlg = showDlg
        #浏览数据目录
        self.inputPushButton.clicked.connect(self.on_data_dir_clicked)
        #浏览处理结果目录
        self.outputPushButton.clicked.connect(self.on_data_op_clicked)
        
        #开始转换处理
        self.convertButton.clicked.connect(self.on_process_button_clicked)

        #关闭对话框
        self.closeButton.clicked.connect(self.on_close_button_clicked)

        self.settings = QSettings('XingqiuCompany', 'dataFormatConvert')
        self.inputLineEdit.setText(self.settings.value('data_path', ''))
        self.outputLineEdit.setText(self.settings.value('op_path', ''))

        dataType = self.settings.value('data_type', 0, type=int)
        if dataType == 0:
            self.radioGdb.setChecked(True)
        else:
            self.radioGpkg.setChecked(True)

    def reset_progress_bar(self):
        self.progressBar.setValue(0)

    def on_data_dir_clicked(self):
        folder_path = QFileDialog.getExistingDirectory(None, "选择数据目录", "")
        self.inputLineEdit.setText(str(folder_path))
        self.settings.setValue('data_path', str(folder_path))

    def on_data_op_clicked(self):
        folder_path = QFileDialog.getExistingDirectory(None, "选择处理结果目录", "")
        self.outputLineEdit.setText(str(folder_path))
        self.settings.setValue('op_path', str(folder_path))

    def process(self, inputPath, inputType, outPath):
        filterName = "*.gdb" if inputType == 0 else "*.gpkg"
        if len(inputPath) == 0:
            if self.showDlg:
                QMessageBox.warning(self, '警告', '数据目录不能为空')
            return
        
        if len(outPath) == 0:
            if self.showDlg:
                QMessageBox.warning(self, '警告', '处理结果目录不能为空')
            return
        if os.path.exists(outPath):
            shutil.rmtree(outPath)  # 删除目标文件夹
        os.makedirs(outPath)
        self.progressBar.setValue(0)        
        if self.showDlg:       
            QApplication.processEvents()
        else:
            print("开始转换")          
        vector_files = glob.glob(os.path.join(inputPath, filterName))
        if len(vector_files) == 0:
            if self.showDlg:
                QMessageBox.information(None, '提示', '没有找到需要进行转换的文件')
            return
        
        #current_os = platform.system()
        #nul_str = 'NUL' if current_os != "Windows" else '/dev/null'

        outFormat = 'GPKG' if inputType == 0 else 'OpenFileGDB'
        prog = 100.0 / len(vector_files)
        idx = 0
        suffixName = ".gpkg" if inputType == 0 else ".gdb"
        
        # 使用subprocess.run来执行命令
        platform_info = platform.system()
        for vector_file in vector_files:
            out_file_name = splitext(split(vector_file)[1])[0] + suffixName
            command = ['ogr2ogr', '-f', outFormat, os.path.join(outPath, out_file_name), vector_file]
            if platform_info == "Windows":
                subprocess.run(command, creationflags=subprocess.CREATE_NO_WINDOW)
            else:
                subprocess.run(command)
            idx = idx + 1
            self.progressBar.setValue((int)(idx * prog))
            if self.showDlg:
                QApplication.processEvents()
            else:
                print('转换进度:' + str((int)(idx * prog)) + '%')
        if self.showDlg:
            self.progressBar.setValue(100)
            QApplication.processEvents()
            QMessageBox.information(None, '提示', '完成')
        else:
            print("转换完成！")  

    def on_process_button_clicked(self):
        filterName = "*.gdb" if self.radioGdb.isChecked() else "*.gpkg"
        if len(self.inputLineEdit.text()) == 0:
            if self.showDlg:
                QMessageBox.warning(self, '警告', '数据目录不能为空')
            return
        
        if len(self.outputLineEdit.text()) == 0:
            if self.showDlg:
                QMessageBox.warning(self, '警告', '处理结果目录不能为空')
            return
        
        self.settings.setValue('data_type', 0 if self.radioGdb.isChecked() else 1)

        
        self.progressBar.setValue(0)
        if self.showDlg:
            QApplication.processEvents()
        
        vector_files = glob.glob(os.path.join(self.inputLineEdit.text(), filterName))
        if len(vector_files) == 0:
            if self.showDlg:
                QMessageBox.information(None, '提示', '没有找到需要进行转换的文件')
            return
        
        #current_os = platform.system()
        #nul_str = 'NUL' if current_os != "Windows" else '/dev/null'

        outFormat = 'GPKG' if self.radioGdb.isChecked() else 'OpenFileGDB'
        prog = 100.0 / len(vector_files)
        idx = 0
        suffixName = ".gpkg" if self.radioGdb.isChecked() else ".gdb"
        
        # 使用subprocess.run来执行命令
        platform_info = platform.system()
        for vector_file in vector_files:
            out_file_name = splitext(split(vector_file)[1])[0] + suffixName
            command = ['ogr2ogr', '-f', outFormat, os.path.join(self.outputLineEdit.text(), out_file_name), vector_file]
            if platform_info == "Windows":
                subprocess.run(command, creationflags=subprocess.CREATE_NO_WINDOW)
            else:
                subprocess.run(command)
            idx = idx + 1
            self.progressBar.setValue((int)(idx * prog))
            if self.showDlg:
                QApplication.processEvents()

        if self.showDlg:
            self.progressBar.setValue(100)
            QApplication.processEvents()
            QMessageBox.information(None, '提示', '完成')
        else:
            print("运行完成！")  
        # self.processCls = processData()
        # self.processCls.setParam(self.data_dir_edit.text(), self.data_check_edit.text(), self.data_op_edit.text(), self.progressBar)
        # #self.thread.progress_signal.connect(self.progressBar.setValue)
        # self.processCls.process()
        # folder_path = QFileDialog.getExistingDirectory(None, "选择数据目录", "")
        # self.dataLineEdit.setText(str(folder_path))
        # self.settings.setValue('data_path', str(folder_path))

    def on_close_button_clicked(self):
        self.close()
