# -*- coding: utf-8 -*-
"""
/***************************************************************************
 dataFormatConvert
                                 A QGIS plugin
 dataFormatConvert
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-01-01
        git sha              : $Format:%H$
        copyright            : (C) 2025 by xing qiu
        email                : xing qiu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .dataFieldOptimization_dialog import dataFieldOptimizationDialog
from .dataEncodeConvert_dialog import dataEncodeConvertDialog
from .dataInDatabase_dialog import dataInDatabaseDialog
from .dataFormatConvert_dialog import dataFormatConvertDialog
from .dataEdgeDetection_dialog import dataEdgeDetectionDialog
from .dataEdgeProcess_dialog import dataEdgeProcessDialog
from .dataScaleAlignment_dialog import dataScaleAlignmentDialog
from .dataUnifiedLogic_dialog import dataUnifiedLogicDialog
import os.path


class dataToolbox:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'dataToolbox_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.dataEdgeCheckActions = []
        self.dataEdgeCheckMenu = self.tr(u'数据接边检查')

        self.standardizationActions = []
        self.standardizationMenu = self.tr(u'标准化入库')

        self.rasterToolActions = []
        self.rasterToolnMenu = self.tr(u'栅格工具箱')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.data_optimization_start = None
        self.data_convert_start = None
        self.data_in_database = None
        self.data_format_start = None

        self.data_edge_detection = None
        self.data_edge_process = None

        self.data_scale_aligment = None
        self.data_unified_logic = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('dataToolbox', message)


    def add_standardization_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.standardizationActions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.standardizationMenu,
                action)

        self.standardizationActions.append(action)

        return action
    
    def add_dataEdgeCheck_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.standardizationActions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.dataEdgeCheckMenu,
                action)

        self.dataEdgeCheckActions.append(action)

        return action
    
    def add_rastertool_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.standardizationActions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToRasterMenu(
                self.rasterToolnMenu,
                action)

        self.rasterToolActions.append(action)

        return action

    def initGui(self):
        
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        data_icon_path = ':/plugins/dataToolbox/image/dataconvert.svg'
        detection_icon_path = ':/plugins/dataToolbox/image/datadetection.svg'
        process_icon_path = ':/plugins/dataToolbox/image/dataprocess.svg'
        optimization_icon_path = ':/plugins/dataToolbox/image/fieldoptimization.svg'
        formart_icon_path = ':/plugins/dataToolbox/image/formartconvert.svg'
        unity_icon_path = ':/plugins/dataToolbox/image/logicalunity.svg'
        alignment_icon_path = ':/plugins/dataToolbox/image/scalealignment.svg'
        database_icon_path = ':/plugins/dataToolbox/image/database.svg'

        self.add_standardization_action(
            optimization_icon_path,
            text=self.tr(u'字段优化'),
            callback=self.dataOptimization,
            parent=self.iface.mainWindow())

        self.add_standardization_action(
            data_icon_path,
            text=self.tr(u'编码转换'),
            callback=self.dataConvert,
            parent=self.iface.mainWindow())
        
        self.add_standardization_action(
            database_icon_path,
            text=self.tr(u'数据入库'),
            callback=self.inDatabase,
            parent=self.iface.mainWindow())

        self.add_standardization_action(
            formart_icon_path,
            text=self.tr(u'格式转换'),
            callback=self.formartConvert,
            parent=self.iface.mainWindow())
        
        # will be set False in run()
        self.data_optimization_start = True
        self.data_convert_start = True
        self.data_in_database = True
        self.data_format_start = True

        self.add_dataEdgeCheck_action(
            detection_icon_path,
            text=self.tr(u'数据接边检测'),
            callback=self.dataEdgeDetection,
            parent=self.iface.mainWindow())
        
        self.add_dataEdgeCheck_action(
            process_icon_path,
            text=self.tr(u'接边处理'),
            callback=self.dataEdgeProcess,
            parent=self.iface.mainWindow())
        
        # will be set False in run()
        self.data_edge_detection = True
        self.data_edge_process = True

        self.add_rastertool_action(
            alignment_icon_path,
            text=self.tr(u'尺度位置对齐'),
            callback=self.dataScaleAlign,
            parent=self.iface.mainWindow())
        self.add_rastertool_action(
            unity_icon_path,
            text=self.tr(u'海陆逻辑统一'),
            callback=self.dataUnifiedLogic,
            parent=self.iface.mainWindow())
        self.data_scale_aligment = True
        self.data_unified_logic = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.dataEdgeCheckActions:
            self.iface.removePluginVectorMenu(
                self.dataEdgeCheckMenu,
                action)
            self.iface.removeToolBarIcon(action)

        for action in self.standardizationActions:
            self.iface.removePluginVectorMenu(
                self.standardizationMenu,
                action)
            self.iface.removeToolBarIcon(action)

        for action in self.rasterToolActions:
            self.iface.removePluginRasterMenu(
                self.rasterToolnMenu,
                action)
            self.iface.removeToolBarIcon(action)
            

    def dataEdgeDetection(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.data_edge_detection == True:
            self.data_edge_detection = False
            self.dataEdgeDetectionDlg = dataEdgeDetectionDialog()

        # show the dialog
        self.dataEdgeDetectionDlg.reset_progress_bar()
        self.dataEdgeDetectionDlg.show()
        # Run the dialog event loop
        result = self.dataEdgeDetectionDlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    def dataEdgeProcess(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.data_edge_process == True:
            self.data_edge_process = False
            self.dataEdgeProcessDlg = dataEdgeProcessDialog()

        # show the dialog
        self.dataEdgeProcessDlg.reset_progress_bar()
        self.dataEdgeProcessDlg.show()
        # Run the dialog event loop
        result = self.dataEdgeProcessDlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    def dataOptimization(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.data_optimization_start == True:
            self.data_optimization_start = False
            self.dataFieldOptimizationDlg = dataFieldOptimizationDialog()

        # show the dialog
        self.dataFieldOptimizationDlg.reset_progress_bar()
        self.dataFieldOptimizationDlg.show()
        # Run the dialog event loop
        result = self.dataFieldOptimizationDlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    def dataConvert(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.data_convert_start == True:
            self.data_convert_start = False
            self.dataFormatConvertDlg = dataEncodeConvertDialog()

        # show the dialog
        self.dataFormatConvertDlg.reset_progress_bar()
        self.dataFormatConvertDlg.show()
        # Run the dialog event loop
        result = self.dataFormatConvertDlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    def inDatabase(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.data_in_database == True:
            self.data_in_database = False
            self.dataInDatabaseDlg = dataInDatabaseDialog()

        # show the dialog
        self.dataInDatabaseDlg.reset_progress_bar()
        self.dataInDatabaseDlg.show()
        # Run the dialog event loop
        result = self.dataInDatabaseDlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    def formartConvert(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.data_format_start == True:
            self.data_format_start = False
            self.dataEncodeConvertDlg = dataFormatConvertDialog()

        # show the dialog
        self.dataEncodeConvertDlg.reset_progress_bar()
        self.dataEncodeConvertDlg.show()
        # Run the dialog event loop
        result = self.dataEncodeConvertDlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    def dataScaleAlign(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.data_scale_aligment == True:
            self.data_scale_aligment = False
            self.dataScaleAlignmentDlg = dataScaleAlignmentDialog()

        # show the dialog
        self.dataScaleAlignmentDlg.reset_progress_bar()
        self.dataScaleAlignmentDlg.show()
        # Run the dialog event loop
        result = self.dataScaleAlignmentDlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    def dataUnifiedLogic(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.data_unified_logic == True:
            self.data_unified_logic = False
            self.dataUnifiedLogicDlg = dataUnifiedLogicDialog()

        # show the dialog
        self.dataUnifiedLogicDlg.reset_progress_bar()
        self.dataUnifiedLogicDlg.show()
        # Run the dialog event loop
        result = self.dataUnifiedLogicDlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
