# -*- coding: utf-8 -*-
"""
/***************************************************************************
 dataFormatConvertDialog
                                 A QGIS plugin
 dataFormatConvert
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-01
        git sha              : $Format:%H$
        copyright            : (C) 2025 by xing qiu
        email                : xing qiu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import glob
from qgis.PyQt import uic, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox, QApplication
from PyQt5.QtCore import QThread, pyqtSignal, QVariant, QSettings
from qgis.core import QgsRasterLayer,QgsProject, QgsRasterResampler, QgsCoordinateReferenceSystem, QgsUnitTypes
from osgeo import gdal, gdalconst
from math import cos, pi

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'dataScaleAlignment_dialog_base.ui'))


class dataScaleAlignmentDialog(QtWidgets.QDialog, FORM_CLASS):
    progress_signal = pyqtSignal(int, str)

    def __init__(self, parent=None, showDlg=True):
        """Constructor."""
        super(dataScaleAlignmentDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.showDlg = showDlg
        self.disConvert = 1.0
        #浏览数据目录
        self.inputPushButton.clicked.connect(self.on_data_dir_clicked)

        #设置保存数据
        self.outputPushButton.clicked.connect(self.on_data_op_clicked)
        
        #开始转换处理
        self.mergeButton.clicked.connect(self.on_process_button_clicked)

        #关闭对话框
        self.closeButton.clicked.connect(self.on_close_button_clicked)
        self.resample_commands = [gdalconst.GRA_NearestNeighbour, gdalconst.GRA_Bilinear, gdalconst.GRA_Cubic, gdalconst.GRA_Average]

        self.settings = QSettings('XingqiuCompany', 'dataScaleAlignment')
        self.inputLineEdit.setText(self.settings.value('data_path', ''))
        self.outResEdit.setText(self.settings.value('out_resolution', '0'))
        raster_files = glob.glob(os.path.join(self.inputLineEdit.text(), "*.tif"))
        self.raster_layers = []
        for raster_file in raster_files:
            raster_layer = QgsRasterLayer(raster_file)
            if raster_layer.isValid() == False:
                continue
            self.raster_layers.append(raster_layer)


        if len(self.raster_layers) > 0:
            layer_unit = format(self.raster_layers[0].rasterUnitsPerPixelX(), '.2f')
            #self.inputDataResolution.setText(layer_unit)
            self.outResEdit.setText(layer_unit)
            uint_type = QgsUnitTypes.toAbbreviatedString(raster_layer.dataProvider().crs().mapUnits())
            if uint_type == QgsUnitTypes.DistanceDegrees:
                raster_extent = self.raster_layers[0].extent()
                center_y = (raster_extent.yMinimum() + raster_extent.yMaximum()) / 2.0
                #赤道1度的长度是111319.55m，对应纬度的1度的长度是
                self.disConvert = cos(center_y * pi / 180.0) * 111319.55
                layer_unit = format(self.raster_layers[0].rasterUnitsPerPixelX() * self.disConvert, '.2f')
            self.outResEdit.setText(layer_unit)
        self.outputLineEdit.setText(self.settings.value('save_path', ''))

        self.comboBox.addItem('最近邻插值')
        self.comboBox.addItem('双线性插值')
        self.comboBox.addItem('双三次插值')
        self.comboBox.addItem('平均重采样')
        self.comboBox.setCurrentIndex(self.settings.value('resample_method', 0, type=int))

        
        self.max_thread_num = 100
        self.progress_signal.connect(self.connect_fun)

    def connect_fun(self, prog, msg_data):
        if self.showDlg:
            self.progressBar.setValue(prog)
        else:
            print("当前进度:" + str(prog) + "%")

        if prog >= 100:
            if self.showDlg:
                QMessageBox.information(None, '提示', msg_data)
            else:
                print("运行完成！")

    def on_data_dir_clicked(self):
        folder_path = QFileDialog.getExistingDirectory(None, "选择数据目录", "")
        self.inputLineEdit.setText(str(folder_path))
        self.settings.setValue('data_path', str(folder_path))

        raster_files = glob.glob(os.path.join(self.inputLineEdit.text(), "*.tif"))
        self.raster_layers = []
        for raster_file in raster_files:
            raster_layer = QgsRasterLayer(raster_file)
            if raster_layer.isValid() == False:
                continue
            self.raster_layers.append(raster_layer)

        #按分辨率降序排列
        self.raster_layers = sorted(self.raster_layers, key=lambda x: -x.rasterUnitsPerPixelX())

        if len(self.raster_layers) == 0:
            if self.showDlg:  
                QMessageBox.warning(self, '警告', '未找到任何有效的拼接数据')
            return
        
        layer_unit = format(self.raster_layers[0].rasterUnitsPerPixelX(), '.2f')
        #self.inputDataResolution.setText(layer_unit)
        
        #uint_type = QgsUnitTypes.toAbbreviatedString(raster_layer.dataProvider().crs().mapUnits())
        uint_type = raster_layer.dataProvider().crs().mapUnits()
        self.disConvert = 1.0
        if uint_type == QgsUnitTypes.DistanceDegrees:

            raster_extent = self.raster_layers[0].extent()
            center_y = (raster_extent.yMinimum() + raster_extent.yMaximum()) / 2.0
            #赤道1度的长度是111319.55m，对应纬度的1度的长度是
            self.disConvert = cos(center_y * pi / 180.0) * 111319.55
            layer_unit = format(self.raster_layers[0].rasterUnitsPerPixelX() * self.disConvert, '.2f')
     
        self.outResEdit.setText(layer_unit)

        # self.label_5.setText(uint_type)
        #self.label_6.setText(uint_type)

    def reset_progress_bar(self):
        self.progressBar.setValue(0)

    def on_data_op_clicked(self):
        if self.checkBox.isChecked():
            save_path, _ = QFileDialog.getSaveFileName(None, "选择保存路径", self.outputLineEdit.text(), "GeoTIFF (*.tif)")
            self.outputLineEdit.setText(save_path)
            self.settings.setValue('save_path', save_path)
        else:
            folder_path = QFileDialog.getExistingDirectory(None, "选择保存目录", "")
            self.outputLineEdit.setText(str(folder_path))
            self.settings.setValue('save_path', str(folder_path))

    def warp_callback(self, pct, message, user_data):
        if pct < 1.0:
            self.progress_signal.emit((int)(pct*100.0), "")
            return
        self.progress_signal.emit(100, "完成")

    def process(self, inputPath, outPath, merge, outRes, resampleType):
        if len(inputPath) == 0:
            if self.showDlg:  
                QMessageBox.warning(self, '警告', '数据目录不能为空')
            return
        
        if len(outPath) == 0:
            if self.showDlg:  
                QMessageBox.warning(self, '警告', '保存路径不能为空')
            return

        raster_files = glob.glob(os.path.join(inputPath, "*.tif"))
        self.raster_layers = []
        for raster_file in raster_files:
            raster_layer = QgsRasterLayer(raster_file)
            if raster_layer.isValid() == False:
                continue
            self.raster_layers.append(raster_layer)

        #按分辨率降序排列
        self.raster_layers = sorted(self.raster_layers, key=lambda x: -x.rasterUnitsPerPixelX())
        #self.settings.setValue('resample_method', self.comboBox.currentIndex())
        if len(self.raster_layers) > 0:
            self.disConvert = 1.0
            #self.inputDataResolution.setText(layer_unit)
            #uint_type = QgsUnitTypes.toAbbreviatedString(raster_layer.dataProvider().crs().mapUnits())
            uint_type = raster_layer.dataProvider().crs().mapUnits()
            if uint_type == QgsUnitTypes.DistanceDegrees:
                raster_extent = self.raster_layers[0].extent()
                center_y = (raster_extent.yMinimum() + raster_extent.yMaximum()) / 2.0
                #赤道1度的长度是111319.55m，对应纬度的1度的长度是
                self.disConvert = cos(center_y * pi / 180.0) * 111319.55
            outRes = outRes / self.disConvert

        if len(self.raster_layers) == 0:
            if self.showDlg:  
                QMessageBox.warning(self, '警告', '未找到任何有效的拼接数据')
            return

        #dstSRS = self.raster_layers[0].crs()
        resample_method = self.resample_commands[resampleType]
        if merge:
            raster_files = []
            for raster_layer in self.raster_layers:
                raster_files.append(raster_layer.source())
            opts = gdal.WarpOptions(resampleAlg=resample_method,xRes=outRes, yRes=outRes, multithread= True, format = 'GTiff')
            gdal.Warp(outPath, raster_files, options=opts)
        else:
            prog = 100.0 / len(self.raster_layers)
            idx = 0
            for raster_layer in self.raster_layers:
                raster_files = []
                raster_files.append(raster_layer.source())
                opts = gdal.WarpOptions(resampleAlg=resample_method,xRes=outRes, yRes=outRes, multithread= True, format = 'GTiff')
                gdal.Warp(os.path.join(outPath, os.path.split(raster_layer.source())[-1]), raster_files, options=opts)
                idx = idx + 1
                self.progressBar.setValue((int)(idx * prog))
                if self.showDlg:
                    QApplication.processEvents()   
                else:               
                    print("当前进度:" + str((int)(idx * prog)) + "%")   
        if self.showDlg:
            self.progressBar.setValue(100)
            QApplication.processEvents()
            QMessageBox.information(None, '提示', '完成')
        else:
            print("运行完成！")   

    def on_process_button_clicked(self):
        if len(self.inputLineEdit.text()) == 0:
            if self.showDlg:  
                QMessageBox.warning(self, '警告', '数据目录不能为空')
            return
        
        if len(self.outputLineEdit.text()) == 0:
            if self.showDlg:  
                QMessageBox.warning(self, '警告', '保存路径不能为空')
            return

        self.settings.setValue('resample_method', self.comboBox.currentIndex())

        if len(self.raster_layers) == 0:
            if self.showDlg:  
                QMessageBox.warning(self, '警告', '未找到任何有效的拼接数据')
            return
        
        #dstSRS = self.raster_layers[0].crs()
        resample_method = self.resample_commands[self.comboBox.currentIndex()]
        if self.checkBox.isChecked():
            out_res = self.raster_layers[0].rasterUnitsPerPixelX()
            raster_files = []
            for raster_layer in self.raster_layers:
                raster_files.append(raster_layer.source())
            try:
                out_res = float(self.outResEdit.text()) / self.disConvert
            except ValueError:
                    out_res = self.raster_layers[0].rasterUnitsPerPixelX()
            opts = gdal.WarpOptions(resampleAlg=resample_method,xRes=out_res, yRes=out_res, multithread= True, format = 'GTiff', callback=self.warp_callback)
            gdal.Warp(self.outputLineEdit.text(), raster_files, options=opts)
        else:
            prog = 100.0 / len(self.raster_layers)
            idx = 0
            for raster_layer in self.raster_layers:
                out_res = raster_layer.rasterUnitsPerPixelX()
                raster_files = []
                raster_files.append(raster_layer.source())
                try:
                    out_res = float(self.outResEdit.text()) / self.disConvert
                except ValueError:
                        out_res = raster_layer.rasterUnitsPerPixelX()
                opts = gdal.WarpOptions(resampleAlg=resample_method,xRes=out_res, yRes=out_res, multithread= True, format = 'GTiff')
                gdal.Warp(os.path.join(self.outputLineEdit.text(), os.path.split(raster_layer.source())[-1]), raster_files, options=opts)
                idx = idx + 1
                self.progressBar.setValue((int)(idx * prog))
                if self.showDlg: 
                    QApplication.processEvents()   

        if self.showDlg:
            self.progressBar.setValue(100)
            QApplication.processEvents()  
            QMessageBox.information(None, '提示', '完成')
        else:
            print("运行完成！")                

    def on_close_button_clicked(self):
        self.close()
